- name: Verify variables are set
  assert:
    that: "{{ item }} is defined"
    msg: Run erp_get_build role first
  with_items:
    - erp_debian_installer_environment
    - erp_build_number

# TODO: Replace with API call, once supported.
- name: Upload build to Cambridge Lab
  pause:
    prompt: "Upload ./builds/debian-{{erp_debian_installer_environment}}/{{erp_build_number}}/ files to http://172.27.80.1:5000/admin/images with description 'debian-installer {{erp_debian_installer_environment}} Build {{erp_build_number}}'. Press <enter> key when complete"

# TODO: Replace with API call, once supported.
- name: Edit Machines
  pause:
    prompt: "In Mr. Provisioner, modify each machine in your host group to {{erp_build_number}}. <enter> once complete"

# TODO: Replace with API call, once supported.
- name: Reboot machines and install OS
  pause:
    prompt: "In Mr. Provisioner, PXE Reboot each machine to install new OS. <enter> once complete"
