galaxy_info:
  author: Dan Rue <dan.rue@linaro.org>
  description: Provision a host in the Cambridge lab.
  company: Linaro

  license: BSD

  min_ansible_version: 2.2

  galaxy_tags: []

dependencies: []
