- hosts: all_erp
  vars:
    squad_environment: production
    debian_installer_environment: staging

  pre_tasks:
    - set_fact:
        erp_squad_auth_token: "{{squad_auth_tokens[squad_environment]}}"

  roles:
    - role: erp_get_build
      delegate_to: localhost
      run_once: true
    - role: erp_provision_cambridge_host
      delegate_to: localhost
      when: "'cambridge_erp' in group_names"
    - role: erp_provision_austin_host
      delegate_to: qa-pxe
      when: "'austin_erp' in group_names"
    - role: erp_run_test_suite
